### ISSUE TITLE
Create a Nexth version with Tailwind

### ISSUE THREAD

**Issue by wslyvh** [wslyvh/nexth#13]
I'd love to see a version of Nexth using Tailwind instead of Chakra UI. Probably keep it on a separate branch.

**Comment by Envoy-VC** [comment]
Hi, I have this repo called boilr3, it's similar to Nexth but it uses Rainbow Kit, wagmi and Tailwind. what do you think about that?

https://github.com/Envoy-VC/boilr3

**Comment by wslyvh** [comment]
Looks great! Love your index page

**Comment by Envoy-VC** [comment]
Thanks, it was inspired from Next.js maybe we can use this repo as the tailwind version for another branch, but before that i will start migrating it to ethers v1.0.0. what do you say?

**Comment by wslyvh** [comment]
I think that's fine! This is definitely low-prio, but a nice 'Good first' issue if someone wants to jump in

RE boil3 - you should submit it to useWeb3 as well. I keep track of a lot of stater kits and boilerplates :)
https://www.useweb3.xyz/starter-kits
