### ISSUE TITLE
when I run the project , there is an error, how to fix it?

### ISSUE THREAD

**Issue by 256yangwei** [wslyvh/nexth#15]
PS D:\projects\js_projects\nexth> npm run dev

> nexth@0.1.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
error - ./src/pages/_app.tsx:3:0
Module not found: Can't resolve 'components/layout/Layout'
  1 | import type { AppProps } from 'next/app'
  2 | // import { Layout } from 'components/layout'
> 3 | import { Layout } from 'components/layout/Layout'
  4 | import { Web3Provider } from 'providers/Web3'
  5 | import { ChakraProvider } from 'providers/Chakra'
  6 | import { useIsMounted } from 'hooks/useIsMounted'

https://nextjs.org/docs/messages/module-not-found
wait  - compiling...
error - ./src/pages/_app.tsx:2:0
Module not found: Can't resolve 'components/layout'
  1 | import type { AppProps } from 'next/app'
> 2 | import { Layout } from 'components/layout'
  3 | // import { Layout } from 'components/layout/Layout'
  4 | import { Web3Provider } from 'providers/Web3'
  5 | import { ChakraProvider } from 'providers/Chakra'

https://nextjs.org/docs/messages/module-not-found

![image](https://github.com/wslyvh/nexth/assets/33602361/e4007f8c-3a21-4376-9812-1aec1855053e)

**Comment by wslyvh** [comment]
Did you install everything successfully?

Please run `yarn` or `npm install` first.
Then you can run `yarn dev` or `npm run dev`

**Comment by 256yangwei** [comment]
I have run npm install ,  I cannot find the 'Layout' form path 'compents/layout'，is it correct？
![image](https://github.com/wslyvh/nexth/assets/33602361/0da08500-b1e2-4097-8b91-5b57171b019e)

**Comment by 256yangwei** [comment]
I run npm install first, then run npm run dev，but the the error still exists.
![image](https://github.com/wslyvh/nexth/assets/33602361/bab16d6e-dd86-4070-9774-144c5f7e69e0)

**Comment by 256yangwei** [comment]
Which version of Node.js, npm, and yarn is used in the project?

**Comment by wslyvh** [comment]
yarn -v 1.22.18
npm -v 8.15.0
node -v v16.17.1

I usually prefer yarn over npm. Can you see if that work?
Otherwise share a bit more a bit more on your setup? Device / OS / software versions?

**Comment by wslyvh** [comment]
Someone else seemed to have a similar issues that was solved by switching to yarn
See #20

Closing issue
