### ISSUE TITLE
Error about loader after npm install

### ISSUE THREAD

**Issue by btc520** [wslyvh/nexth#20]
Hi, I got following errors after run npm install and npm dev run, I am an entry-level player, could you please check? 

error - ./node_modules/react-native/index.js
Module parse failed: Unexpected token (14:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| // Components
> import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
| import typeof ActivityIndicator from './Libraries/Components/ActivityIndicator/ActivityIndicator';
| import typeof Button from './Libraries/Components/Button';

**Comment by wslyvh** [comment]
Did you get any errors or logs from installing? 

What versions of NPM and nodejs do you use? 
Maybe also share a bit more info on your setup? Device / OS / other software?

**Comment by btc520** [comment]
Hello Sir, it works with YARN! 

It didn't works with NPM, and I represent the problem below  

I tired to install react-native and it gave the error above. 

node version v18.16.0, npm 9.5.1.

1. npm run dev output: 
====
warn  - ./node_modules/@wagmi/connectors/node_modules/@walletconnect/universal-provider/dist/index.es.js
Module not found: Can't resolve 'react-native' in 'D:\projects\nexth\node_modules\@wagmi\connectors\node_modules\@walletconnect\universal-provider\dist'
warn  - ./node_modules/@wagmi/connectors/node_modules/@walletconnect/universal-provider/dist/index.es.js
Module not found: Can't resolve 'react-native' in 'D:\projects\nexth\node_modules\@wagmi\connectors\node_modules\@walletconnect\universal-provider\dist'
====

2. http://localhost:3000/ output: 
====
Unhandled Runtime Error
Error: No wagmi config found. Ensure you have set up a config: https://wagmi.sh/react/config

Call Stack
,,,,
====
