### ISSUE TITLE
Installing Shadcn bricks the Interface

### ISSUE THREAD

**Issue by mergd** [wslyvh/nexth#24]
First of all, great starter – really nice looking

One issue I am noticing is that when I install the shadcn ui library, the UI fails over, and then when I boot up the development server, it just bricks and shows the /not-found page when the page loads.

I was using bun, but same issue pops up using yarn – driving me up the wall 🙃

**Comment by mergd** [comment]
Issue was with shadcn mistakingly creating a new app folder when there already is an app folder within the src/

soz!

**Comment by wslyvh** [comment]
All good. Hope it all worked out.
