### ISSUE TITLE
getting this error when running yarn after following install instructions.

### ISSUE THREAD

**Issue by alexrmacleod** [wslyvh/nexth#30]
node 18

error:
`yarn run v1.22.21
$ yarn workspaces -pt run dev

> nexth
$ next dev
  ▲ Next.js 13.5.4
  - Local:        http://localhost:3000
  - Environments: .env.local

 ✓ Ready in 2.5s
 ○ Compiling /page ...
 ⚠ ../../node_modules/@walletconnect/keyvaluestorage/dist/cjs/node-js/db.js
Module not found: Can't resolve 'lokijs' in '/Users/alex/Documents/nexth/node_modules/@walletconnect/keyvaluestorage/dist/cjs/node-js'

Import trace for requested module:
../../node_modules/@walletconnect/keyvaluestorage/dist/cjs/node-js/db.js
../../node_modules/@walletconnect/keyvaluestorage/dist/cjs/node-js/index.js
../../node_modules/@walletconnect/keyvaluestorage/dist/cjs/index.js
../../node_modules/@walletconnect/core/dist/index.cjs.js
../../node_modules/@walletconnect/sign-client/dist/index.cjs.js
../../node_modules/@walletconnect/universal-provider/dist/index.es.js
../../node_modules/@walletconnect/ethereum-provider/dist/index.es.js
../../node_modules/@wagmi/connectors/dist/walletConnect.js
../../node_modules/@wagmi/core/dist/connectors/walletConnect.js
../../node_modules/wagmi/dist/connectors/walletConnect.js
../../node_modules/@web3modal/wagmi/dist/esm/src/utils/defaultWagmiReactConfig.js
../../node_modules/@web3modal/wagmi/dist/esm/exports/react.js
./src/context/Web3.tsx

../../node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in '/Users/alex/Documents/nexth/node_modules/node-fetch/lib'

Import trace for requested module:
../../node_modules/node-fetch/lib/index.js
../../node_modules/cross-fetch/dist/node-ponyfill.js
../../node_modules/@walletconnect/jsonrpc-http-connection/dist/cjs/http.js
../../node_modules/@walletconnect/jsonrpc-http-connection/dist/cjs/index.js
../../node_modules/@walletconnect/universal-provider/dist/index.es.js
../../node_modules/@walletconnect/ethereum-provider/dist/index.es.js
../../node_modules/@wagmi/connectors/dist/walletConnect.js
../../node_modules/@wagmi/core/dist/connectors/walletConnect.js
../../node_modules/wagmi/dist/connectors/walletConnect.js
../../node_modules/@web3modal/wagmi/dist/esm/src/utils/defaultWagmiReactConfig.js
../../node_modules/@web3modal/wagmi/dist/esm/exports/react.js
./src/context/Web3.tsx

../../node_modules/pino/lib/tools.js
Module not found: Can't resolve 'pino-pretty' in '/Users/alex/Documents/nexth/node_modules/pino/lib'

Import trace for requested module:
../../node_modules/pino/lib/tools.js
../../node_modules/pino/pino.js
../../node_modules/@walletconnect/logger/dist/cjs/index.js
../../node_modules/@walletconnect/universal-provider/dist/index.es.js
../../node_modules/@walletconnect/ethereum-provider/dist/index.es.js
../../node_modules/@wagmi/connectors/dist/walletConnect.js
../../node_modules/@wagmi/core/dist/connectors/walletConnect.js
../../node_modules/wagmi/dist/connectors/walletConnect.js
../../node_modules/@web3modal/wagmi/dist/esm/src/utils/defaultWagmiReactConfig.js
../../node_modules/@web3modal/wagmi/dist/esm/exports/react.js
./src/context/Web3.tsx
Lit is in dev mode. Not recommended for production! See https://lit.dev/msg/dev-mode for more information.
Multiple versions of Lit loaded. Loading multiple versions is not recommended. See https://lit.dev/msg/multiple-versions for more information.
 ⚠ ../../node_modules/@walletconnect/keyvaluestorage/dist/cjs/node-js/db.js
Module not found: Can't resolve 'lokijs' in '/Users/alex/Documents/nexth/node_modules/@walletconnect/keyvaluestorage/dist/cjs/node-js'

Import trace for requested module:
../../node_modules/@walletconnect/keyvaluestorage/dist/cjs/node-js/db.js
../../node_modules/@walletconnect/keyvaluestorage/dist/cjs/node-js/index.js
../../node_modules/@walletconnect/keyvaluestorage/dist/cjs/index.js
../../node_modules/@walletconnect/core/dist/index.cjs.js
../../node_modules/@walletconnect/sign-client/dist/index.cjs.js
../../node_modules/@walletconnect/universal-provider/dist/index.es.js
../../node_modules/@walletconnect/ethereum-provider/dist/index.es.js
../../node_modules/@wagmi/connectors/dist/walletConnect.js
../../node_modules/@wagmi/core/dist/connectors/walletConnect.js
../../node_modules/wagmi/dist/connectors/walletConnect.js
../../node_modules/@web3modal/wagmi/dist/esm/src/utils/defaultWagmiReactConfig.js
../../node_modules/@web3modal/wagmi/dist/esm/exports/react.js
./src/context/Web3.tsx

../../node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in '/Users/alex/Documents/nexth/node_modules/node-fetch/lib'

Import trace for requested module:
../../node_modules/node-fetch/lib/index.js
../../node_modules/cross-fetch/dist/node-ponyfill.js
../../node_modules/@walletconnect/jsonrpc-http-connection/dist/cjs/http.js
../../node_modules/@walletconnect/jsonrpc-http-connection/dist/cjs/index.js
../../node_modules/@walletconnect/universal-provider/dist/index.es.js
../../node_modules/@walletconnect/ethereum-provider/dist/index.es.js
../../node_modules/@wagmi/connectors/dist/walletConnect.js
../../node_modules/@wagmi/core/dist/connectors/walletConnect.js
../../node_modules/wagmi/dist/connectors/walletConnect.js
../../node_modules/@web3modal/wagmi/dist/esm/src/utils/defaultWagmiReactConfig.js
../../node_modules/@web3modal/wagmi/dist/esm/exports/react.js
./src/context/Web3.tsx

../../node_modules/pino/lib/tools.js
Module not found: Can't resolve 'pino-pretty' in '/Users/alex/Documents/nexth/node_modules/pino/lib'

Import trace for requested module:
../../node_modules/pino/lib/tools.js
../../node_modules/pino/pino.js
../../node_modules/@walletconnect/logger/dist/cjs/index.js
../../node_modules/@walletconnect/universal-provider/dist/index.es.js
../../node_modules/@walletconnect/ethereum-provider/dist/index.es.js
../../node_modules/@wagmi/connectors/dist/walletConnect.js
../../node_modules/@wagmi/core/dist/connectors/walletConnect.js
../../node_modules/wagmi/dist/connectors/walletConnect.js
../../node_modules/@web3modal/wagmi/dist/esm/src/utils/defaultWagmiReactConfig.js
../../node_modules/@web3modal/wagmi/dist/esm/exports/react.js
./src/context/Web3.tsx
 ⚠ ../../node_modules/@walletconnect/keyvaluestorage/dist/cjs/node-js/db.js
Module not found: Can't resolve 'lokijs' in '/Users/alex/Documents/nexth/node_modules/@walletconnect/keyvaluestorage/dist/cjs/node-js'

Import trace for requested module:
../../node_modules/@walletconnect/keyvaluestorage/dist/cjs/node-js/db.js
../../node_modules/@walletconnect/keyvaluestorage/dist/cjs/node-js/index.js
../../node_modules/@walletconnect/keyvaluestorage/dist/cjs/index.js
../../node_modules/@walletconnect/core/dist/index.cjs.js
../../node_modules/@walletconnect/sign-client/dist/index.cjs.js
../../node_modules/@walletconnect/universal-provider/dist/index.es.js
../../node_modules/@walletconnect/ethereum-provider/dist/index.es.js
../../node_modules/@wagmi/connectors/dist/walletConnect.js
../../node_modules/@wagmi/core/dist/connectors/walletConnect.js
../../node_modules/wagmi/dist/connectors/walletConnect.js
../../node_modules/@web3modal/wagmi/dist/esm/src/utils/defaultWagmiReactConfig.js
../../node_modules/@web3modal/wagmi/dist/esm/exports/react.js
./src/context/Web3.tsx

../../node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in '/Users/alex/Documents/nexth/node_modules/node-fetch/lib'

Import trace for requested module:
../../node_modules/node-fetch/lib/index.js
../../node_modules/cross-fetch/dist/node-ponyfill.js
../../node_modules/@walletconnect/jsonrpc-http-connection/dist/cjs/http.js
../../node_modules/@walletconnect/jsonrpc-http-connection/dist/cjs/index.js
../../node_modules/@walletconnect/universal-provider/dist/index.es.js
../../node_modules/@walletconnect/ethereum-provider/dist/index.es.js
../../node_modules/@wagmi/connectors/dist/walletConnect.js
../../node_modules/@wagmi/core/dist/connectors/walletConnect.js
../../node_modules/wagmi/dist/connectors/walletConnect.js
../../node_modules/@web3modal/wagmi/dist/esm/src/utils/defaultWagmiReactConfig.js
../../node_modules/@web3modal/wagmi/dist/esm/exports/react.js
./src/context/Web3.tsx

../../node_modules/pino/lib/tools.js
Module not found: Can't resolve 'pino-pretty' in '/Users/alex/Documents/nexth/node_modules/pino/lib'

Import trace for requested module:
../../node_modules/pino/lib/tools.js
../../node_modules/pino/pino.js
../../node_modules/@walletconnect/logger/dist/cjs/index.js
../../node_modules/@walletconnect/universal-provider/dist/index.es.js
../../node_modules/@walletconnect/ethereum-provider/dist/index.es.js
../../node_modules/@wagmi/connectors/dist/walletConnect.js
../../node_modules/@wagmi/core/dist/connectors/walletConnect.js
../../node_modules/wagmi/dist/connectors/walletConnect.js
../../node_modules/@web3modal/wagmi/dist/esm/src/utils/defaultWagmiReactConfig.js
../../node_modules/@web3modal/wagmi/dist/esm/exports/react.js
./src/context/Web3.tsx
 ⚠ ../../node_modules/@walletconnect/keyvaluestorage/dist/cjs/node-js/db.js
Module not found: Can't resolve 'lokijs' in '/Users/alex/Documents/nexth/node_modules/@walletconnect/keyvaluestorage/dist/cjs/node-js'

Import trace for requested module:
../../node_modules/@walletconnect/keyvaluestorage/dist/cjs/node-js/db.js
../../node_modules/@walletconnect/keyvaluestorage/dist/cjs/node-js/index.js
../../node_modules/@walletconnect/keyvaluestorage/dist/cjs/index.js
../../node_modules/@walletconnect/core/dist/index.cjs.js
../../node_modules/@walletconnect/sign-client/dist/index.cjs.js
../../node_modules/@walletconnect/universal-provider/dist/index.es.js
../../node_modules/@walletconnect/ethereum-provider/dist/index.es.js
../../node_modules/@wagmi/connectors/dist/walletConnect.js
../../node_modules/@wagmi/core/dist/connectors/walletConnect.js
../../node_modules/wagmi/dist/connectors/walletConnect.js
../../node_modules/@web3modal/wagmi/dist/esm/src/utils/defaultWagmiReactConfig.js
../../node_modules/@web3modal/wagmi/dist/esm/exports/react.js
./src/context/Web3.tsx

../../node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in '/Users/alex/Documents/nexth/node_modules/node-fetch/lib'

Import trace for requested module:
../../node_modules/node-fetch/lib/index.js
../../node_modules/cross-fetch/dist/node-ponyfill.js
../../node_modules/@walletconnect/jsonrpc-http-connection/dist/cjs/http.js
../../node_modules/@walletconnect/jsonrpc-http-connection/dist/cjs/index.js
../../node_modules/@walletconnect/universal-provider/dist/index.es.js
../../node_modules/@walletconnect/ethereum-provider/dist/index.es.js
../../node_modules/@wagmi/connectors/dist/walletConnect.js
../../node_modules/@wagmi/core/dist/connectors/walletConnect.js
../../node_modules/wagmi/dist/connectors/walletConnect.js
../../node_modules/@web3modal/wagmi/dist/esm/src/utils/defaultWagmiReactConfig.js
../../node_modules/@web3modal/wagmi/dist/esm/exports/react.js
./src/context/Web3.tsx

../../node_modules/pino/lib/tools.js
Module not found: Can't resolve 'pino-pretty' in '/Users/alex/Documents/nexth/node_modules/pino/lib'

Import trace for requested module:
../../node_modules/pino/lib/tools.js
../../node_modules/pino/pino.js
../../node_modules/@walletconnect/logger/dist/cjs/index.js
../../node_modules/@walletconnect/universal-provider/dist/index.es.js
../../node_modules/@walletconnect/ethereum-provider/dist/index.es.js
../../node_modules/@wagmi/connectors/dist/walletConnect.js
../../node_modules/@wagmi/core/dist/connectors/walletConnect.js
../../node_modules/wagmi/dist/connectors/walletConnect.js
../../node_modules/@web3modal/wagmi/dist/esm/src/utils/defaultWagmiReactConfig.js
../../node_modules/@web3modal/wagmi/dist/esm/exports/react.js
./src/context/Web3.tsx
 ⚠ ../../node_modules/@walletconnect/keyvaluestorage/dist/cjs/node-js/db.js
Module not found: Can't resolve 'lokijs' in '/Users/alex/Documents/nexth/node_modules/@walletconnect/keyvaluestorage/dist/cjs/node-js'

Import trace for requested module:
../../node_modules/@walletconnect/keyvaluestorage/dist/cjs/node-js/db.js
../../node_modules/@walletconnect/keyvaluestorage/dist/cjs/node-js/index.js
../../node_modules/@walletconnect/keyvaluestorage/dist/cjs/index.js
../../node_modules/@walletconnect/core/dist/index.cjs.js
../../node_modules/@walletconnect/sign-client/dist/index.cjs.js
../../node_modules/@walletconnect/universal-provider/dist/index.es.js
../../node_modules/@walletconnect/ethereum-provider/dist/index.es.js
../../node_modules/@wagmi/connectors/dist/walletConnect.js
../../node_modules/@wagmi/core/dist/connectors/walletConnect.js
../../node_modules/wagmi/dist/connectors/walletConnect.js
../../node_modules/@web3modal/wagmi/dist/esm/src/utils/defaultWagmiReactConfig.js
../../node_modules/@web3modal/wagmi/dist/esm/exports/react.js
./src/context/Web3.tsx

../../node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in '/Users/alex/Documents/nexth/node_modules/node-fetch/lib'

Import trace for requested module:
../../node_modules/node-fetch/lib/index.js
../../node_modules/cross-fetch/dist/node-ponyfill.js
../../node_modules/@walletconnect/jsonrpc-http-connection/dist/cjs/http.js
../../node_modules/@walletconnect/jsonrpc-http-connection/dist/cjs/index.js
../../node_modules/@walletconnect/universal-provider/dist/index.es.js
../../node_modules/@walletconnect/ethereum-provider/dist/index.es.js
../../node_modules/@wagmi/connectors/dist/walletConnect.js
../../node_modules/@wagmi/core/dist/connectors/walletConnect.js
../../node_modules/wagmi/dist/connectors/walletConnect.js
../../node_modules/@web3modal/wagmi/dist/esm/src/utils/defaultWagmiReactConfig.js
../../node_modules/@web3modal/wagmi/dist/esm/exports/react.js
./src/context/Web3.tsx

../../node_modules/pino/lib/tools.js
Module not found: Can't resolve 'pino-pretty' in '/Users/alex/Documents/nexth/node_modules/pino/lib'

Import trace for requested module:
../../node_modules/pino/lib/tools.js
../../node_modules/pino/pino.js
../../node_modules/@walletconnect/logger/dist/cjs/index.js
../../node_modules/@walletconnect/universal-provider/dist/index.es.js
../../node_modules/@walletconnect/ethereum-provider/dist/index.es.js
../../node_modules/@wagmi/connectors/dist/walletConnect.js
../../node_modules/@wagmi/core/dist/connectors/walletConnect.js
../../node_modules/wagmi/dist/connectors/walletConnect.js
../../node_modules/@web3modal/wagmi/dist/esm/src/utils/defaultWagmiReactConfig.js
../../node_modules/@web3modal/wagmi/dist/esm/exports/react.js
./src/context/Web3.tsx
`

**Comment by wslyvh** [comment]
This is an issue on some important libraries of Web3Modal. 
These should only be warnings and can be safely ignored.

I do believe they recently fixed it, so will try to update the packages to see if the issue still exists.

**Comment by wslyvh** [comment]
Should be fixed with latest upgrades to Wagmi/Viem v2
https://github.com/wslyvh/nexth/commit/f642fa1402d7561079de758a65f6082e7c099481
