### ISSUE TITLE
Open a Discussion Group 

### ISSUE THREAD

**Issue by lawweiliang** [wslyvh/nexth#8]
Hi @wslyvh, thanks for your repo,

Would you mind to create a discussion group that let's everyone discuss the feature they want?

Here is the reference on how to open GitHub `discussion` [^1] . It is free. 😄 

[^1]: https://docs.github.com/en/discussions/quickstart

**Comment by wslyvh** [comment]
To be honest, I'm usually fine with using issues for discussions.
Happy to give this a try though. Thanks for suggesting it

https://github.com/wslyvh/nexth/discussions
